### PR TITLE
[TO REVIEW] chore: create empty files for beer 29

### PR DESCRIPTION
**Pull request by ShauniArima**
Page implémentée. Les données sont en anglais. On peut passer l'API en Français ?
Screenshot_2020-10-14 10 Heads High(1)

### CODE REVIEW

**Review by ClementineBiais — APPROVED** [review]

**Review by rigwild — CHANGES_REQUESTED** [review]
Add the beer image to the homepage catalog 😉

**Comment by ShauniArima** [comment]
Second PR

#30

**Review by rigwild — APPROVED** [review]

**Comment by ShauniArima** [comment]
Oupsi need to change something. Sorry.

**Comment by ShauniArima** [comment]
Updated and ready to merge!

**Review by rigwild — APPROVED** [review]
Better recipe indeed, it must have a good taste 🤔

**Review by Bugsyaya — APPROVED** [review]

**Pull request merged**
